
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";



import AddFriend from "./pages/AddFriend.tsx";
import AdminStore from "./pages/AdminStore.tsx";
import App from "./pages/App.tsx";
import CreateEvent from "./pages/CreateEvent.tsx";
import EditEvent from "./pages/EditEvent.tsx";
import EventDetail from "./pages/EventDetail.tsx";
import Events from "./pages/Events.tsx";
import Feed from "./pages/Feed.tsx";
import FirebaseTest from "./pages/FirebaseTest.tsx";
import Flip from "./pages/Flip.tsx";
import Legal from "./pages/Legal.tsx";
import Login from "./pages/Login.tsx";
import Marketplace from "./pages/Marketplace.tsx";
import MarketplaceProduct from "./pages/MarketplaceProduct.tsx";
import Member from "./pages/Member.tsx";
import Members from "./pages/Members.tsx";
import Orders from "./pages/Orders.tsx";
import ProductDetail from "./pages/ProductDetail.tsx";
import Profile from "./pages/Profile.tsx";
import ProfileSetup from "./pages/ProfileSetup.tsx";
import PwaInstall from "./pages/PwaInstall.tsx";
import SellerDashboard from "./pages/SellerDashboard.tsx";
import ShopifyProductDetail from "./pages/ShopifyProductDetail.tsx";
import Signup from "./pages/Signup.tsx";
import Store from "./pages/Store.tsx";
import VeteranHub from "./pages/VeteranHub.tsx";
import VeteranVerification from "./pages/VeteranVerification.tsx";

export const userRoutes: RouteObject[] = [



	{ path: "/add-friend", element: <UserGuard><AddFriend /></UserGuard> },
	{ path: "/addfriend", element: <UserGuard><AddFriend /></UserGuard> },
	{ path: "/admin-store", element: <UserGuard><AdminStore /></UserGuard> },
	{ path: "/adminstore", element: <UserGuard><AdminStore /></UserGuard> },
	{ path: "/", element: <App /> },
	{ path: "/create-event", element: <CreateEvent /> },
	{ path: "/createevent", element: <CreateEvent /> },
	{ path: "/edit-event", element: <EditEvent /> },
	{ path: "/editevent", element: <EditEvent /> },
	{ path: "/event-detail", element: <EventDetail /> },
	{ path: "/eventdetail", element: <EventDetail /> },
	{ path: "/events", element: <Events /> },
	{ path: "/feed", element: <Feed /> },
	{ path: "/firebase-test", element: <UserGuard><FirebaseTest /></UserGuard> },
	{ path: "/firebasetest", element: <UserGuard><FirebaseTest /></UserGuard> },
	{ path: "/flip", element: <UserGuard><Flip /></UserGuard> },
	{ path: "/legal", element: <Legal /> },
	{ path: "/login", element: <Login /> },
	{ path: "/marketplace", element: <Marketplace /> },
	{ path: "/marketplace-product", element: <MarketplaceProduct /> },
	{ path: "/marketplaceproduct", element: <MarketplaceProduct /> },
	{ path: "/member", element: <Member /> },
	{ path: "/members", element: <UserGuard><Members /></UserGuard> },
	{ path: "/orders", element: <UserGuard><Orders /></UserGuard> },
	{ path: "/product-detail", element: <UserGuard><ProductDetail /></UserGuard> },
	{ path: "/productdetail", element: <UserGuard><ProductDetail /></UserGuard> },
	{ path: "/profile", element: <UserGuard><Profile /></UserGuard> },
	{ path: "/profile-setup", element: <ProfileSetup /> },
	{ path: "/profilesetup", element: <ProfileSetup /> },
	{ path: "/pwa-install", element: <UserGuard><PwaInstall /></UserGuard> },
	{ path: "/pwainstall", element: <UserGuard><PwaInstall /></UserGuard> },
	{ path: "/seller-dashboard", element: <SellerDashboard /> },
	{ path: "/sellerdashboard", element: <SellerDashboard /> },
	{ path: "/shopify-product-detail", element: <ShopifyProductDetail /> },
	{ path: "/shopifyproductdetail", element: <ShopifyProductDetail /> },
	{ path: "/signup", element: <Signup /> },
	{ path: "/store", element: <Store /> },
	{ path: "/veteran-hub", element: <VeteranHub /> },
	{ path: "/veteranhub", element: <VeteranHub /> },
	{ path: "/veteran-verification", element: <VeteranVerification /> },
	{ path: "/veteranverification", element: <VeteranVerification /> },

];
